#' Construct table arrangements
#'
#' Arrangements describe how variables in table content are mapped to rows and columns in the materialized table.
#'
#' Ordering of variables is also part of a tttable arrangement, but can be handled in several ways that do not require explicit handling in tttable:
#' - store variables as factors and use the levels to control order
#' - use existing data ordering

#' Adapted from code from the `ggplot2::aes()` function for guidance and inspiration, and aspires to using the quotation semantics of a [quoting function][rlang::quotation], or maybe `tidyselect` helpers?
#'
#' * several nested variables mapped to either rows or columns

#'
#' @export
#' @examples
#' a1  <- arr("V1")
#' a2  <- arr(c("V1", "V2"))
#' a3  <- arr(rows = "V1", cols = "V2")
#' a1b <- arr(V1)
#' a2b <- arr(vars(V1, V2))
#' a3b <- arr(rows = V1, cols = V2)
#' @importFrom dplyr vars
#'
#' @import purrr
arr <- function(rows, cols) {

  #character vectors only right now
  rows <- if(rlang::is_missing(rows)) rlang::syms(c()) else rlang::syms(rows)
  cols <- if(rlang::is_missing(cols)) rlang::syms(c()) else rlang::syms(cols)

  arr <- new_arr(rows, cols)
  arr
}

#rows and cols are lists of symbols generated by syms
new_arr <- function(rows, cols) {
  stopifnot(is.list(rows))
  stopifnot(is.list(cols))

  structure(
    list(
      rows = rows,
      cols = cols
    ),
    class = "tt_arr"
  )
}

#' attach an arrangement a tttable
#'
#' should the original creation of a tttable imply an arrangement the way ggplot does? Would be nice to defer I think.
#'@examples
#'
tt_arrange <- function(tttable, mapping = arr(), ...) {
  # TODO
  stop("to be implemented")
}

#' @export
print.tt_arr <- function(x, ...) {
  cat("tttable arrangement: \n")

  if (length(x) == 0) {
    cat("<empty>\n")
  } else {
    values <- vapply(x, rlang::quo_label, character(1))
    bullets <- paste0("* ", format(paste0("`", names(x), "`")), " -> ", values, "\n")

    cat(bullets, sep = "")
  }

  invisible(x)
}
